### ISSUE TITLE
Cómo hacer que en el router pueda cargarse una partida (sin datos) pero que se muestre sin tener el id

### ISSUE THREAD

**Issue by ErickaSanchezCorral1998** [Proyecto-Integral-Web/154654#1]
[practica_uno/practica_vue/src/router/index.js](url)

 {
    // rutas dinamicas, donde no_partida puede ser diferente para cargar dicha partida
    path: '/juego-1/:no_partida',
    name: 'partida', // asignamos nombre, debe ser único y original
    component: Partida // Declaramos componente
  },

**Comment by betoflakes** [comment]
Es imposible cargar algo que no existe. Por eso primero tenemos que crear la partida, para luego mostrarla. Por eso necesitamos una lista de partidas, porque así podemos crearlas y luego seleccionarlas para mostrarlas.
