### ISSUE TITLE
Al hacer refresh de en el perfil tengo que volver a iniciar sesión

### ISSUE THREAD

**Issue by ErickaSanchezCorral1998** [Proyecto-Integral-Web/154654#2]
[practica_uno/practica_vue/src/components/ProfileForm.vue](url)

**Comment by betoflakes** [comment]
[Esta es la solución para controlar el estado de la sesión](https://github.com/Proyecto-Integral-Web/PaperScissorsRock/blob/40ea34645293281906ff02a6532c98fca67e057a/src/main.js#L19)
[En la view del login checamos para hacer el redirect](https://github.com/Proyecto-Integral-Web/PaperScissorsRock/blob/40ea34645293281906ff02a6532c98fca67e057a/src/views/Login.vue#L26)

No faltes el jueves para la explicación.
